version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: irctc_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: irctc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: irctc_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/irctc
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  pgdata:
